import {
  cyan500, cyan700,
  pinkA200,
  grey100, grey300, grey400, grey500,
  white, darkBlack, fullBlack,
  deepPurple200
} from 'material-ui/styles/colors';
import { fade } from 'material-ui/utils/colorManipulator';
import spacing from 'material-ui/styles/spacing';

export default {
  spacing: spacing,
  fontFamily: 'Roboto, sans-serif',
  palette: {
    primary1Color: '#455A64',
    primary2Color: '#607D8B',
    primary3Color: '#CFD8DC',
    accent1Color: '#CDDC39',
    accent2Color: grey100,
    accent3Color: grey500,
    textColor: '#212121',
    alternateTextColor: '#FFFFFF',
    canvasColor: white,
    borderColor: '#BDBDBD',
    disabledColor: fade(darkBlack, 0.3),
    pickerHeaderColor: cyan500,
    clockCircleColor: fade(darkBlack, 0.07),
    shadowColor: fullBlack,
  },
};

/* Palette generated by Material Palette - materialpalette.com/blue-grey/lime */

// .dark-primary-color    { background: #455A64; }
// .default-primary-color { background: #607D8B; }
// .light-primary-color   { background: #CFD8DC; }
// .text-primary-color    { color: #FFFFFF; }
// .accent-color          { background: #CDDC39; }
// .primary-text-color    { color: #212121; }
// .secondary-text-color  { color: #757575; }
// .divider-color         { border-color: #BDBDBD; }
